lint:
  files_exist:
  - CODE_OF_CONDUCT.md
  - assets/nf-core-syph-pipe_logo_light.png
  - docs/images/nf-core-syph-pipe_logo_light.png
  - docs/images/nf-core-syph-pipe_logo_dark.png
  - .github/ISSUE_TEMPLATE/config.yml
  - .github/workflows/awstest.yml
  - .github/workflows/awsfulltest.yml
  files_unchanged:
  - CODE_OF_CONDUCT.md
  - assets/nf-core-syph-pipe_logo_light.png
  - docs/images/nf-core-syph-pipe_logo_light.png
  - docs/images/nf-core-syph-pipe_logo_dark.png
  - .github/ISSUE_TEMPLATE/bug_report.yml
  multiqc_config:
  - report_comment
  nextflow_config:
  - manifest.name
  - manifest.homePage
nf_core_version: 2.14.1
repository_type: pipeline
template:
  author: Nishant Singh
  description: Nextflow pipeline for preprocessing, assembly, and analysis of Syphilis
    WGS data
  name: syph-pipe
  prefix: PHO
